tally/urls.py
from django.conf.urls import url

#from django.contrib.auth import views as auth_views
from . import views

app_name = 'tally'
urlpatterns = [
        url(r'^$', views.index, name='index'),
        # url(r'^login', auth_views.login, {'template_name': 'admin/login.html'}, name='login'),
        # url(r'^logout', views.logout_view, name='logout'),
        # url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
  
        url(r'^students/$', views.students, name='students'),
        url(r'^students/(?P<student_id>[a-zA-Z0-9_]+)/$', 
            views.student_detail, name='student_detail'),
        url(r'^add/student/$', views.add_student, name='add_student'),
  
        url(r'^businesses/$', views.businesses, name='businesses'),
        url(r'^businesses/(?P<business_id>[a-zA-Z0-9_]+)/$', 
            views.business_detail, name='business_detail'),
        
        url(r'^purchases/$', views.purchases, name='purchases'),
        url(r'^purchases/(?P<purchase_id>[a-zA-Z0-9_]+)/$',
            views.purchase_detail, name='purchase_detail'),
        url(r'^add/purchase/student/(?P<student_id>[a-zA-z0-9_]+)/$',
            views.add_purchase_student, name='add_purchase_student'),
       ]

tally/templates/tally/add_student.html
{% extends 'tally/base.html' %}

{% block content %}

<h1> Add Student </h1>

<table>
    <form action="/tally/add/student/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
</table>

{% endblock %}

tally/templates/tally/base.html
{% load staticfiles %}
<html>
    <head>
        <title> Scrip Tracking </title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <!--    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'> -->
        <link rel="stylesheet" href="{% static 'css/tally.css' %}">
    </head>
    <body>
        <div>
            <h1><a href="/tally/">Scrip Tally</a></h1>
        </div>
        <div>
            <p style='text-align:left; margin-left:10px; margin-right:10px'>
            <a href='/tally/students/'>Students </a> |
            <a href='/tally/businesses/'> Businesses </a> | 
            <a href='/tally/purchases/'> Purchases </a> | 
            <a href='/'> Main Index </a>
                <span style='float:right'>        
                    <a href='/accounts/login?next=/tally/'> Login </a> | 
                    <a href='/accounts/logout'> Logout</a>
                    <br/>
                    {% if username  %}
                        Logged in as: {{ username }}
                    {% else %}
                        Not logged in
                    {% endif %}
                </span>
            </p>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

tally/templates/tally/business_detail.html
{% extends 'tally/base.html' %}

{% block content %}

<h1 style='margin-left:10px'> {{ business.name.capitalize }} </h1>



{% endblock %}

tally/templates/tally/businesses.html
{% extends 'tally/base.html' %}

{% block content %}

<h1> All Businesses </h1>
<a href=''> Add new business</a>

<ul>
    {% for bus in businesses %}
    <li><a href={% url 'tally:business_detail' bus.id %}>{{ bus.name }}</a></li>
    {% endfor %}

</ul>



{% endblock %}

tally/templates/tally/index.html
{% extends 'tally/base.html' %}

{% block content %}

    <h1> Tally Index </h1>

    <ul>
        <li><a href="{% url 'tally:students' %}">Students</a></li>
        <li><a href="{% url 'tally:businesses' %}">Businesses</a></li>
        <li><a href="{% url 'tally:purchases' %}">Purchases</a></li>
    </ul>
{% endblock %}

tally/templates/tally/login.html
{% extends 'tally/base.html' %}

{% block content %}
<div id='login'>
    <form class='form-horizontal' name='LoginForm' action='/accounts/login?next=/tally/' method='post'>
        {% csrf_token %}

        <div class='control-group'>
            <label class='control-label' for='username'>Username</label>
            <div class='controls'>
                <input type='text' id='username' name='username' placeholder='Username'>
            </div>
        </div>
        <div class='control-group'>
            <label class='control-label' for='password'>Password</label>
            <div class='controls'>
                <input type='password' name='password' id='password' placeholder='Password'>
            </div>
        </div>
        <div class='control-group'>
            <div class='controls'>
                <button type='submit' class='btn'>Login</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

tally/templates/tally/purchase_detail.html
{% extends 'tally/base.html' %}

{% block content %}
<h1 style="margin-left:10px">  
    {{ purchase.student.full_name.title }} -- {{ purchase.business.name.capitalize }} </h1>

<br/>
<table class="center-table">
    <col width='75'>
    <col width='300'>
    <caption><strong> -- Purchase Details -- </strong></caption>
    <tr><th>Desc.</th><td>{{ purchase }}</td></tr>
    <tr><th>Date</th><td>{{ purchase.purchase_date.month }}/{{purchase.purchase_date.day}}/{{purchase.purchase_date.year }}</td></tr>
    <tr><th>Amount</th><td>${{ purchase.amount }}</td></tr>
    <tr><th>%</th><td>{{ percentage }}</td></tr>
</table>


{% endblock %}

tally/templates/tally/purchases.html
{% extends 'tally/base.html' %}

{% block content %}

    <h1> All Purchases </h1>

    <a href='/tally/purchases/'>Add new purchase</a>
    <ul>
        {% for pur in purchases %}
        <li> <a href={% url 'tally:purchase_detail' pur.id %}>{{ pur }}</a></li>
        {% endfor %}
    </ul>





{% endblock %}

tally/templates/tally/student_detail.html
{% extends 'tally/base.html' %}

{% block content %}

    <h2 style="margin-left:10px"> {{ student.full_name.title }} </h2>
    <table border="1" style="float:left; margin-left:10px; margin-right:100px; text-align:center">
        <col width=120>
        <col width=120 >
        <caption><strong> -- Student info -- </strong></caption>
        <tr><th> Enrolled  </td><td> {{ student.enrolled }} </td></tr>
        <tr><th> Phone      </td><td> {{ student.phone }} </td></tr>
        <tr><th> Homeroom  </td><td> {{ student.homeroom }} </td></tr>
        <tr><th> Adults    </td><td> {{ student.adults }}</td></tr>  
    </table> 


    <table border="1" class="center-table" style="float:center">
        <col width="60">
        <col width="75">
        <col width="75">
        <caption><strong> -- Purchase Amounts -- </strong> </caption>
        <tr><th>        </th><th>    Total         </th><th> This Year </th></tr>
        <tr><th> Spent  </th><td> ${{ total_spent }}  </td><td> ${{ thisyear_spent }}</td></tr>
        <tr><th> Earned </th><td> ${{ total_earned }} </td><td> ${{ thisyear_earned }}</td></tr>
    </table>

    <br/>
    <br/>
    <table border="1" class="purchase-table">
        <col width="10">
        <col width="300">
        <col width="75">
        <col width="75">
        <caption><strong> -- Purchases
                          <a href={% url 'tally:add_purchase_student' student.id %}>add new</a>
                          -- </strong></caption>
        <tr><th> No. </th><th> Desc. </th><th> Amount </th><th> Date </th></tr>
        {% for pur in purchases %}
          <tr>
            <th> {{ forloop.counter }}</th>
            <td> <a href={% url 'tally:purchase_detail' pur.id %}>{{ pur }}</a></td>
            <td> {{ pur.amount }} </td>
            <td>{{pur.purchase_date.month}}/{{pur.purchase_date.day}}/{{pur.purchase_date.year}} </td>
          </tr>
        {% endfor %}


{% endblock %}

tally/templates/tally/students.html
{% extends 'tally/base.html' %}

{% block content %} 

   <h1> All Students </h1>


    <a href="{% url 'tally:add_student' %}">Add a new student</a>

    {% if student_list %}
        <ul>
            {% for student in student_list %}
                <li><a href="{% url 'tally:student_detail' student.id %}">{{ student.full_name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No Student listed...</p>
    {% endif %}

{% endblock %}